---
{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "local-storage-metrics-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: local-storage-metrics-exporter-service
    app.kubernetes.io/name: local-storage-metrics-exporter
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/component: local-storage-metrics-exporter
    app.kubernetes.io/name: local-storage-metrics-exporter
{{- end }}
