apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ephemeral-storage-exporter
  namespace: kube-system
  labels:
    app: ephemeral-storage-exporter
spec:
  selector:
    matchLabels:
      app: ephemeral-storage-exporter
  template:
    metadata:
      labels:
        app: ephemeral-storage-exporter
    spec:
      containers:
        - name: exporter
          image: your-dockerhub-username/ephemeral-storage-exporter:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
          securityContext:
            runAsUser: 1000
            runAsGroup: 3000
            allowPrivilegeEscalation: false
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
