apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ephemeral-storage-exporter
  namespace: kube-system
  labels:
    app: ephemeral-storage-exporter
    kubernetes.io/name: ephemeral-storage-exporter
    kubernetes.io/app: ephemeral-storage-exporter
spec:
  selector:
    matchLabels:
      kubernetes.io/name: ephemeral-storage-exporter
      kubernetes.io/app: ephemeral-storage-exporter
  template:
    metadata:
      labels:
        kubernetes.io/name: ephemeral-storage-exporter
        kubernetes.io/app: ephemeral-storage-exporter
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: exporter
          image: ghcr.io/amirhnajafiz/ephemeral-storage-metrics-exporter:latest
          ports:
            - containerPort: 8080
          env:
            - name: K8SESE_PORT
              value: 8080
            - name: K8SESE_DEBUG
              value: false
            - name: K8SESE_INTERVAL
              value: 10
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
      terminationGracePeriodSeconds: 30
